// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MisionDbContext))]
    [Migration("20220222103744_Infrastructure.Migrations")]
    partial class InfrastructureMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21");

            modelBuilder.Entity("Infrastructure.MisionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("RobotsQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surface")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mision");
                });

            modelBuilder.Entity("Infrastructure.RobotCommadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MisionModelId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int>("XCoordinate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YCoordinate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MisionModelId");

                    b.ToTable("RobotCommadModel");
                });

            modelBuilder.Entity("Infrastructure.RobotOutputModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MisionModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XCoordinate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YCoordinate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MisionModelId");

                    b.ToTable("RobotOutputModel");
                });

            modelBuilder.Entity("Infrastructure.RobotCommadModel", b =>
                {
                    b.HasOne("Infrastructure.MisionModel", null)
                        .WithMany("RobotsCommands")
                        .HasForeignKey("MisionModelId");
                });

            modelBuilder.Entity("Infrastructure.RobotOutputModel", b =>
                {
                    b.HasOne("Infrastructure.MisionModel", null)
                        .WithMany("RobotsResult")
                        .HasForeignKey("MisionModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
