// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MisionDbContext))]
    [Migration("20220223120851_Infrastructure.Migrations")]
    partial class InfrastructureMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21");

            modelBuilder.Entity("Domain.Models.MisionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecutionDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RobotsInputs")
                        .HasColumnType("TEXT");

                    b.Property<int>("RobotsQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RobotsResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scents")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mision");
                });
#pragma warning restore 612, 618
        }
    }
}
